config/routes.rb
Hackvote::Application.routes.draw do

  resources :hackdays, :only => [:index, :create, :show] do
    resources :hacks, :only => [:create, :show, :update]
  end
  

  root :to => 'hackdays#index'

end

app/models/hack.rb
class Hack < ActiveRecord::Base
  belongs_to :hackday
  attr_accessible :hackday_id, :hack_url, :img_url, :title, :votes, :owner, :description 

  validates :title, :hackday, :description, :presence => true
  validates :title, :length => { :minimum => 3 }

end

app/models/hackday.rb
class Hackday < ActiveRecord::Base
  has_many :hacks
  attr_accessible :day, :img_url, :title

  validates :title, :day, :presence => true
  validates :title, :length => { :minimum => 3 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :votes_left_key
  def votes_left_key 
    "votes_left_" + session[:current_hackday_id].to_s
  end
end

app/controllers/hackdays_controller.rb
class HackdaysController < ApplicationController
  def index
    # launch the homepage, which has a link to the latest hack.  
    @hackday = Hackday.order("created_at").last
  end

  def create
    # hackday popup posts here to create new hackdays, data is stored, and we respond with json.
    @hackday = Hackday.create(params[:hackday])
    if @hackday.valid?
      redirect_to hackday_path(@hackday)
    else
      render :status => :bad_request, :text => @hackday.errors.full_messages
    end
  end

  def show
    # find the hackday in the url ex domain.com/hackdays/1
    @hackday = Hackday.find_by_id(params[:id])
    # page has a link to prev day, so try to get the prev day, may not exist though.  
    @prev_hackday = Hackday.where("created_at < ?", @hackday.created_at).last
    # each user session get 3 votes per hackday.  
    if session[votes_left_key()] == nil
      #session previously did not exist.  initialize
      session[votes_left_key()] = 3
    end

    @votes_left = session[votes_left_key()]
  end

end

app/controllers/hacks_controller.rb
class HacksController < ApplicationController

  def create
    @hackday = Hackday.find_by_id(params[:hackday_id])
    hack = @hackday.hacks.create(params[:hack])
    if hack.valid?
      redirect_to hackday_path(@hackday)
    else
      render :status => :bad_request, :text => hack.errors.full_messages
    end
  end

  def update
    hack = Hack.find_by_id(params[:id])
    if session[votes_left_key()] < 1
      # out of votes.
      success = false
      msg = "out of votes"
    else
      hack.votes += 1
      if hack.save
        session[votes_left_key()] -= 1        
        msg = "Voted Successfully"
        success = true
      else
        render :status => :bad_request, :text => @hack.errors.full_messages
      end
    end
    render :json => { :success => success, :msg => msg, :votes => hack.votes }
  end

  def show
    # display the particular hack
    @hack = Hack.find_by_id(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hackdays_helper.rb
module HackdaysHelper
end

app/helpers/hacks_helper.rb
module HacksHelper
end

app/views/hackdays/index.html.erb
<html> 
<head>

</head>
<title>Heyzap Hack Log</title>
<body>

  <div id="main_container" class="container" data-controller="homepage"> 
    <div class="row"> 
      <div class="col-md-12"> 
        <div class="upper_container">
          <% if @hackday %>
          <%= link_to 'hackdays', hackday_path(@hackday) %>
          <% end %>
        </div>
      </div>
    </div>
    <div class="row"> 
      <div class="col-md-12 front_logo">
        <img src="/assets/heyzap.png">
        <h1>hacklog</h1>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12">
        <div class="lower_container"> 
          <button id="new_hack_button" type="button" class="btn btn-default">New Hack</button>
        </div>
      </div>
    </div>
  </div>
  <div id="myModal" class="modal fade" id="myModal1" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <h1> add new HACKDAY </h1>
        <%= form_for :hackday, :html => { :id => "new_hackday_form" }, :url => hackdays_path do |h| %>
          <% [:title, :img_url, :day].each do |attribute| %>
            <p>
              <%= h.label attribute %><br>
              <%= h.text_field attribute %>
            </p>
          <% end %>
          <%= h.submit 'Create Hackday', :class => "btn btn-default" %>
        <% end %>

        <!-- <form id="new_hackday_form" accept-charset="UTF-8" action="/hackdays" method="post">
          <p>
            <label for="hackday_title">Title</label><br>
            <input id="hackday_title" name="title" size="30" type="text" value="">
          </p>
          <p>
            <label for="hackday_img_url">Img url</label><br>
            <input id="hackday_img_url" name="img_url" size="30" type="text" value="">
          </p>

          <p>
            <label for="hackday_day">Day</label><br>
            <input id="hackday_day" name="day" size="30" type="text">
          </p>
          <p>
            <button id="hackday_submit_button" type="button" class="btn btn-default">Submit</button>
          </p>
        </form> -->

      </div>
    </div>
  </div>


</body>
</html>

app/views/hackdays/show.html.erb
<html> 
  <head> 
  </head>
<body> 

  <div id="main_container" class="container" data-controller="hackday">
    <h1> Hackday: <%= @hackday.title %> </h1>
    <h2> these hacks belong to date: <%= @hackday.day %> </h2>
    <h2> votes left <div id="votes_left"><%= @votes_left %><div> </h2> 
    <% if @prev_hackday %>
      <%= link_to "Prevoius Day", hackday_path(@prev_hackday), { :class=>"btn btn-default" } %>
    <% end %>
    

    <% @hackday.hacks.each do |hack| %>
    <div style="border: 1px solid black;">
      <h1><%= link_to hack.title, hackday_hack_path(hack) %></h1>
      <h3> By <%= hack.owner %> </h3>
      <h3> url: <%= hack.hack_url %> </h3>
      <h3> votes: <div class="vote_holder"><%= hack.votes %><div> </h3>
      <button type="button" class="btn btn-default vote_button" data-vote-url=<%= hackday_hack_path(hack) %>>Vote for this Hack</button>
    </div>
    <% end %>

    <h1> add new hack </h1>
    <%= form_for :hack, url: hackday_hacks_path(@hackday) do |h| %>
      <% [:title, :img_url, :hack_url, :owner, :description].each do |attribute| %>
        <p>
          <%= h.label attribute %><br>
          <%= h.text_field attribute %>
        </p>
      <% end %>
    <p>
      <%= h.submit 'Create Hack' %>
    </p>
    <% end %>

  </div>
</body>
</html>

app/views/hacks/show.html.erb
<h1> SHOWING HACK # <%= @hack.id %> </h1>

<h2> owner is <%= @hack.owner.name %> </h2>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hackvote</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>